<?php

/**
 * @file
 * ILO base theme companion module.
 */

use Symfony\Component\Finder\Finder;

/**
 * Implements hook_library_info_build().
 */
function ilo_base_theme_companion_library_info_build() {
  /** @var \Drupal\ilo_base_theme_companion\ComponentsLocator $locator */
  $locator = \Drupal::service('ilo_base_theme_companion.components_locator');
  $css_files = (new Finder())->files()->name('*.css')->in($locator->getComponentDirectory());

  $styles = [];
  foreach ($css_files as $css_file) {
    // Get relative path of CSS file and add CSS file to the library.
    $relative_path = $css_file->getRelativePathname();
    $styles['dist/components/' . $relative_path] = [];
  }

  return [
    'components' => [
      'css' => [
        'base' => $styles,
      ],
    ],
  ];
}
