name: CI
on: [pull_request]
jobs:
  code-sniffer:
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: "8.2"
    steps:
      - name: clone
        uses: actions/checkout@v4
      - run: make up-dist
      - name: test
        run: docker compose exec -T dist ./vendor/bin/phpcs
  automated-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["8.2"]
    env:
      PHP_VERSION: ${{ matrix.php_version }}
    steps:
      - name: clone
        uses: actions/checkout@v4
      - run: make up-dist
      - name: fix permissions
        run: docker compose exec -T dist chmod -R 777 web/sites
      - name: test
        # To avoid file permissions issues, we run the phpunit with user 33, which is the same as the apache user id container.
        run: docker compose exec -u 33 -T dist ./vendor/bin/phpunit
