name: ci
on: [pull_request]
jobs:
  code-sniffer:
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: "8.2"
    steps:
      - name: clone
        uses: actions/checkout@v2
      - run: make up
      - name: build
        run: docker-compose exec -T php composer install
      - name: test
        run: docker-compose exec -T php ./vendor/bin/phpcs
  automated-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["8.2"]
        composer_command: ["composer install"]
    env:
      PHP_VERSION: ${{ matrix.php_version }}
    steps:
      - name: clone
        uses: actions/checkout@v2
      - run: make up
      - name: install
        run: make install
      - name: test
        run: docker-compose exec -T php ./vendor/bin/phpunit
